indent_style = "Block"
reorder_imports = true
tab_spaces = 4
hard_tabs = true
brace_style = "PreferSameLine"
combine_control_expr = true
fn_single_line = true
single_line_if_else_max_width = 100
empty_item_single_line = true
single_line_if_else = true
max_width = 120
comment_width = 80
format_code_in_doc_comments = true
struct_lit_single_line = true
struct_lit_width = 80
